### PR TITLE
Feature/refactoring project structure

### PR DESCRIPTION
**Pull request by ShevchenyaIlya**
* MongoDB hosted on MongoDB Atlas
* Flask application deployed to AWS Elastic Beanstalk
* Frontend part deployed to AWS S3 (link: http://document-collaboration-system.s3-website-us-east-1.amazonaws.com/)

The website was treated as corporate and according to the original assignment all roles and users were considered assigned. To access website you only need username.  
List of available users to log in website:
- ilya - Role: "Lawyer", company: "LaTex"
- anton - Role: "Economist", company: "LaTex"
- ivan - Role: "General director", company: "LaTex"
- itech_0 - Role: "Lawyer", company: "itech"
- itech_1 - Role: "Economist", company: "itech"
- itech_2 - Role: "General director", company: "itech"

The full description of the task can be found in the file "Online text editor.pdf" located in this branch

### CODE REVIEW

**Review by gmltA — COMMENTED** [review]
I'm getting errors during login process. Seems like the back-end is unavailable.

**Comment by ShevchenyaIlya** [comment]
> I'm getting errors during login process. Seems like the back-end is unavailable.

Everything works fine for me. The problem may have arisen from the Safari if you are using it.

**Comment by gmltA** [comment]
I'm using Chrome. The error is caused by the server unavailability. This typically has nothing to do with the browser.

**Comment by ShevchenyaIlya** [comment]
> I'm using Chrome. The error is caused by the server unavailability. This typically has nothing to do with the browser.

@gmltA Я перепроверил, пишет, что сервер активен, потом попробовал зайти - всё сработало. Сейчас тоже не работает?


https://user-images.githubusercontent.com/50058232/116134124-3955c080-a6d8-11eb-9646-e4ec70e777b5.mp4

**Review by gmltA — COMMENTED** [review]
Right. I can offer you <kbd>8</kbd> now, but I will check your project more precisely later.

**Comment by ShevchenyaIlya** [comment]
> Right. I can offer you 8 now, but I will check your project more precisely later.

@gmltA Это как финальная оценка? Я просто сделал также поддержку двух тем и в качестве CI автоматический деплоймент с помощью GitHub Actions(код самого action также прикреплен к данному pr). И могу ли я отключить задеплоенный сервер, потому что Free Tier закончился и AWS стал уже снимать деньги?

**Comment by gmltA** [comment]
А гэта вы ўсё скончылі ўжо? Можна правяраць як гатовы праект?

**Comment by ShevchenyaIlya** [comment]
> А гэта вы ўсё скончылі ўжо? Можна правяраць як гатовы праект?

@gmltA Думаю да

**Review by gmltA — APPROVED** [review]
Выглядае добра. Гэта <kbd>9</kbd>. Столькі ж пайдзе ў рэкамендацыю.

Поспехаў!

**Comment by ShevchenyaIlya** [comment]
> Выглядае добра. Гэта 9. Столькі ж пайдзе ў рэкамендацыю.
> 
> Поспехаў!

@gmltA Понял, спасибо!

**Pull request merged**
